#Executable name
EXECUTABLE := insertionSeries

#Compiler
CC      := gcc
CFLAGS  := -std=c11 -Wall -Wextra -O2

#Source file
SRC     := main.c \
           utility/pairList.c \
           utility/intList.c \

OBJ     := $(SRC:.c=.o)

insertionseries: $(OBJ)
	$(CC) $(OBJ) -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXECUTABLE)
